extends Node

var branches = 2
var tiers = 5
var knowledge_points = 5

var upgrades = {
	"Caligraphy": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 1,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
	"Dummy1": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 2,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
	"Dummy2": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 2,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
	"Dummy3": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 3,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
	"Dummy4": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 4,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
	"Dummy5": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 4,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
	"Dummy6": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 4,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
	"Dummy7": {
		"name": "Caligraphy",
		"label": "Gain the ability to write",
		"cost": 100,
		"branch": 1,
		"tier": 5,
		"unlocked": false,
		"bought": false,
		"requires": {},
		"id": 1,
		"btn": null,
	},
}
